[project]
name = "oit-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "opencv-python>=4.12.0.88",
    "python-dotenv>=1.2.1",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
]
